---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"
    pull_request:
      types: [opened, reopened, synchronize]
      branches:
        - "master"


jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0
        
      
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: autorun.zip
          # List of excluded files / directories
          exclusions: |
            deploy*
            configScripts*
            *.git*
            ak.features.json
            .gitignore
            README.md
            audio.json
            config.json
            network.json
            video.json
            window.json

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{github.ref_type == 'tag'}}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            autorun.zip
            ak.features.json
        id: "automatic-release-tag"

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{github.event_name == 'pull_request'}}
        with:
          automatic_release_tag: '${{github.ref_name}}'
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            autorun.zip
            ak.features.json
        id: "automatic-release-pull"

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{github.ref_type == 'branch'}}
        with:
          automatic_release_tag: 'latest'
          title: "Latest Development Build"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            autorun.zip
            ak.features.json
        id: "automatic-release-latest"

